spring:
  #resources.static-locations: classpath:/dist/
  profiles:
    active: st
  data:
    jpa:
      repositories:
        enabled: true
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled:  true
      file-size-threshold: 1MB
      max-file-size:  2MB
      max-request-size:  10MB
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
security:
  enable-csrf: false
  basic:
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
wechat:
  mp:
    appId: wxd45ea849e28c0d42
    secret: 6b14f343294929d96ff1be2f720d130b
    token: hlwerbv123nsf
    aesKey: u3hX2kQdo1hvQWRkg9MjOahuw3zY7nxmargMNf9TJW7
---
server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mysql://598af1f083b62.sh.cdb.myqcloud.com:5428/mktj?useUnicode=true&characterEncoding=utf-8&useSSL=false
      #url: jdbc:mysql://localhost:3306/mktj?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: wz718718
      #password: 123456
      driverClassName: com.mysql.jdbc.Driver
  http:
    multipart:
      location: c:/upload_temp
management:
  port: 54001
  health:
    sensitive:
      enabled: false
web:
  maximumSessions: 100
photo:
  path: c:/project/mktj/photo/
---
server:
  port: 80
spring:
  profiles: st
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:mysql://10.66.245.8:3306/mktj?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: wz718718
      driverClassName: com.mysql.jdbc.Driver
  http:
    multipart:
      location: /opt/projects/mktj/temp
web:
  maximumSessions: 1
photo:
  path: /opt/projects/mktj/photo/

